version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - revive

formatters:
  enable:
    - gofmt
    - goimports

formatters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: microservices-bigtech

linters-settings:
  revive:
    rules:
      - name: exported
        severity: warning

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
